spring:
  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  datasource:

    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://cjone-dev-rds.c5syk8q4mlad.ap-northeast-2.rds.amazonaws.com:5432/cjone_dev_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  data:
    redis:
      host: cjone-redis-cache-fpxtkj.serverless.apn2.cache.amazonaws.com
      port: 6379
#      username: yerim159
#      password: ${REDIS_PASSWORD}
      # π’΅ [μ¶”κ°€] μ „μ†΅ μ¤‘ μ•”νΈν™”λ¥Ό ν™μ„±ν™”ν–μΌλ―€λ΅ SSL/TLS μ„¤μ •μ„ μ¶”κ°€
#      ssl:
#        enabled: true


jwt:
  access-token-expiration: 10800
  secret: 5FwsE49eeFcoKguHGRSCOuo0WcOPVU++yav+yCDMfBM=