spring:
  jpa:
    hibernate:
      ddl-auto: create
    # ğŸ’¡ ì´ ë¶€ë¶„ì´ ìˆ˜ì •ë˜ì—ˆìŠµë‹ˆë‹¤.
    # propertiesëŠ” jpa ì•„ë˜ì— ìœ„ì¹˜í•´ì•¼ í•©ë‹ˆë‹¤.
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    # ğŸ’¡ driver-class-nameê³¼ dialectëŠ” ì„œë¡œ ë‹¤ë¥¸ ê²½ë¡œì— ìˆìŠµë‹ˆë‹¤.
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://cjone-dev-db.c5syk8q4mlad.ap-northeast-2.rds.amazonaws.com:5432/cjone-dev-db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  data:
    redis:
      host: cjone-dev-redis-master.default.svc.cluster.local
      port: 6379

# ì´í•˜ JWT ì„¤ì •ì€ ê·¸ëŒ€ë¡œ ìœ ì§€
jwt:
  access-token-expiration: 10800
  secret: 5FwsE49eeFcoKguHGRSCOuo0WcOPVU++yav+yCDMfBM=